### ISSUE TITLE
fredtool

### ISSUE THREAD

**Issue by leaveyww** [zoogie/Fredtool#1]
I have entered the right movable and dsiware bin but I keep getting an error message

**Comment by zoogie** [comment]
That's really not enough info, but go ahead and post your more detailed help request in the discord below instead of here.

https://discord.gg/C29hYvh

**Comment by alananas75** [comment]
how to enter movable and dsiware please

**Comment by zoogie** [comment]
Sigh. 
https://discord.gg/C29hYvh
https://3ds.hacks.guide
